# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/onenote_LLM_interface',
                'doc_host': 'https://trangml.github.io',
                'git_url': 'https://github.com/trangml/onenote_LLM_interface',
                'lib_path': 'onenote_LLM_interface'},
  'syms': {'onenote_LLM_interface.core': {'onenote_LLM_interface.core.foo': ('core.html#foo', 'onenote_LLM_interface/core.py')}}}
